services:
    web:
        container_name: googlesheet-web
        image: nginx:latest
        ports:
            - "8084:80"
        volumes:
            - ./:/googlesheet
            - ./docker/ngnix/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - php
    php:
        restart: always
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: googlesheet-php
        working_dir: /googlesheet/
        volumes:
            - ./:/googlesheet
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        expose:
            - "9000"
        depends_on:
            - database
    database:
        image: mysql:8.0
        container_name: googlesheet-mysql
        restart: unless-stopped
        ports:
            - "3346:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - mysql_data:/var/lib/mysql
volumes:
    persistent-erp:
    mysql_data:
